version: "3.9"

services:
  auth:
    build: .
    command: uvicorn services.auth_service.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=your_secret_key_here

  search:
    build: .
    command: uvicorn services.search_service.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=your_secret_key_here
